import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import github from "@/../public/github.svg";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ apiData }) {
  return (
    <>
      <Head>
        <title>Dylan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <a href="https://github.com/DylanDev92" target="_blank">
            <Image src={github} alt="my github"></Image>
          </a>
        </header>

        <div className={styles.introduction}>
          <h2>Hello! I am</h2>
          <h1>
            <span className={styles.name}>
              Dylan, <br />
            </span>
            I’m a web and game developer.
          </h1>
        </div>
        <p>
          I am a self-taught web and game developer currently studying at
          Centennial College. At just 17 years old, I am motivated to continue
          developing my coding skills. With a passion for coding, I am excited
          to see where my skills and dedication take me in the industry.
        </p>
        <a href="https://github.com/DylanDev92" target="_blank">
          <button>Visit GitHub</button>
        </a>
      </main>

      <section className={styles.skills}>
        <h1 className={styles.name}>Skills</h1>
        <p>
          These are my skills, constantly improving them and learning more
          technologies.
        </p>

        {apiData?.skills.map((item, key) => {
          return (
            <div className={styles.list} key={key}>
              <h1 className={styles.name}>{item.Name}</h1>
              {item.Skills.map((skill, key) => {
                return <p key={key}>{skill}</p>;
              })}
            </div>
          );
        })}
      </section>

      <section className={styles.projects}>
        <h1 className={styles.name}>My projects</h1>
        <p>These are the projects my most relevant projects, more in GitHub.</p>
        {apiData?.projects.map((project, key) => {
          return (
            <div className={styles.project} key={key}>
              <h1>{project.Name}</h1>
              <p>{project.Description}</p>
              <a href={project.Link} target="_blank">
                <button>Open GitHub</button>
              </a>
            </div>
          );
        })}
      </section>

      <footer className={styles.footer}>
        <hr />
        <p>
          This portfolio is built in <strong>Next.js</strong>
        </p>
      </footer>
    </>
  );
}
export async function getServerSideProps(ctx){
  const response = await fetch("http://0.0.0.0:" + process.env.PORT +"/api/projectlist");
  const apiData = await response.json();
  console.log(apiData);

  return {
    props:{
      apiData: apiData
    }
  }
}